# gitlab CI config for uvm-python.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
#image: python:latest
image: python:3.7.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/
    - iverilog/
    - iverilog/*.o

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  #- git clone https://github.com/cocotb/cocotb.git
  #- pip install ./cocotb
  #- pip install cocotb-coverage
  #- pip install regex
  - pip install -r ci/requirements.txt
  - apt-get update -qq
  - apt-get install -y -qq flex bison gperf
  - bash ci/install_iverilog.sh
  - ln -s src/uvm ./uvm

lint:
  script:
    - pip install flake8
    - make lint

test:
  script:
    - export SIM=icarus
    - make test --jobs=4 || exit 1
    # - RET_VAL=`grep failure results.log`
    # - python setup.py test
    # - pip install tox flake8  # you can also use tox
    # - tox -e py36,flake8

#coverage:
#  script:
#    - pip install coverage coveralls
#    - make cov-all
#    - coveralls
#  artifacts:
#    paths:
#      - htmlcov/

#docs:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd docs ; make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
